name: Collect and Prepare Posts
on:
  schedule:
    - cron: '0 0 * * *' # Каждый день в полночь UTC
  workflow_dispatch:

jobs:
  collect_and_prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run collector
        run: python src/github/collector.py
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_SESSION_STRING: ${{ secrets.TELEGRAM_SESSION_STRING }}
          TELEGRAM_CHANNEL_USERNAME: ${{ secrets.TELEGRAM_CHANNEL_USERNAME }}
          TELEGRAM_CHANNEL_USERNAME_2: ${{ secrets.TELEGRAM_CHANNEL_USERNAME_2 }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      - name: Run formatter
        run: python src/bot/formatter.py
        env:
          CHANNEL_NAMES: ${{ secrets.CHANNEL_NAMES }}
          ADDITIONAL_CHANNELS: ${{ secrets.ADDITIONAL_CHANNELS }}
      - name: Run split_posts
        run: python src/bot/split_posts.py
      - name: Run collector_post
        run: python src/github/collector_post.py
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      - name: Run formated_dev
        run: python src/bot/formated_dev.py
      - name: Run formated_hashnode
        run: python src/bot/formated_hashnode.py
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git commit -m "Daily data collection and preparation" || exit 0
          git push
